version: "3.8"

services:
   api:
    build: .
    container_name: security_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_KEY=WkQzsPW9gQn/q0niJ2F8GtYrQv1GiHTSDRDu8EReQhY=
      - JWT_ISSUER=MiApi
      - JWT_AUDIENCE=MiCliente
      - POSTGRES_DB=projectdb
      - POSTGRES_HOST= db  
      - POSTGRES_USER=projectuser
      - POSTGRES_PASSWORD=supersecret
    depends_on:
      db:
        condition: service_healthy
   db:
    image: postgres:16
    container_name: projectpg
    restart: unless-stopped
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - projectdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projectuser -d projectdb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  projectdata:
